### ISSUE TITLE
latest version doesn't have a jar

### ISSUE THREAD

**Issue by RyanCR03** [PigCart/particle-rain#21]
the latest release (2.0.2) is not compiled into a jar file and only has the source code to download.

**Comment by PigCart** [comment]
yes i didn't finish setting up mc-publish.
you can still grab builds from the artifacts at the bottom of the action pages https://github.com/PigCart/particle-rain/actions/runs/4398884308

**Comment by RyanCR03** [comment]
ok, i did that but now its crashing when particles load

[crash-2023-04-04_15.55.29-client.txt](https://github.com/PigCart/particle-rain/files/11153199/crash-2023-04-04_15.55.29-client.txt)
```Unreported exception thrown!
java.lang.NoSuchMethodError: 'void net.minecraft.class_2338.<init>(net.minecraft.class_243)'
	at net.minecraft.class_761.handler$zle000$particlerain$tickRain(class_761.java:4915)
	at net.minecraft.class_761.method_22713(class_761.java)
	at net.minecraft.class_757.method_3182(class_757.java:812)
	at net.minecraft.class_310.method_1574(class_310.java:1890)
	at net.minecraft.class_310.method_1523(class_310.java:1180)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by PigCart** [comment]
yes the latest version is for 1.19.3 not 1.19.4.
